// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQVDe6WNaXs-uzzvHdBgh49c40ZPojDow',
    appId: '1:682334233187:web:6e98bb20ce6c491f778e56',
    messagingSenderId: '682334233187',
    projectId: 'ictproject-ef9cb',
    authDomain: 'ictproject-ef9cb.firebaseapp.com',
    storageBucket: 'ictproject-ef9cb.appspot.com',
    measurementId: 'G-VEGZS5CPWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgy_6Mlnd4Q4KpwSKM6Vhky9fOvuiJh9c',
    appId: '1:682334233187:android:03caaa0e802bc111778e56',
    messagingSenderId: '682334233187',
    projectId: 'ictproject-ef9cb',
    storageBucket: 'ictproject-ef9cb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQVDe6WNaXs-uzzvHdBgh49c40ZPojDow',
    appId: '1:682334233187:web:69b79a83d09bce94778e56',
    messagingSenderId: '682334233187',
    projectId: 'ictproject-ef9cb',
    authDomain: 'ictproject-ef9cb.firebaseapp.com',
    storageBucket: 'ictproject-ef9cb.appspot.com',
    measurementId: 'G-FJ7TSDQX5H',
  );
}
